### ISSUE TITLE
Create new default CiliumConfig

### ISSUE THREAD

**Issue by stianfro** [Intility/charts#5]
Current CiliumConfig must be looked over.

For example: ingressController, gatewayAPI  and their pre-reqs should be enabled.

**Comment by stianfro** [comment]
Example of a semi-updated config:

```
apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  ingressController:
    enabled: true
    loadbalancerMode: shared
    default: true
  cni:
    binPath: /var/lib/cni/bin
    confPath: /var/run/multus/cni/net.d
  hubble:
    enabled: false
    ui:
      enabled: false
    relay:
      enabled: false
    tls:
      enabled: false
  ipam:
    mode: cluster-pool
    operator:
      clusterPoolIPv4PodCIDRList:
        - 10.216.0.0/14
  ipv6:
    enabled: false
  nodePort:
    enabled: true
  operator:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  prometheus:
    serviceMonitor:
      enabled: false
  securityContext:
    privileged: true
  sessionAffinity: true
```
